GET http://localhost:3001/register

#####
POST http://localhost:3001/register/new
Content-Type: application/json

{
"email": "npabhinand@gmail",
 "name": "abhin",
 "phone": "9048407795",
 "usertype":"student",
 "password":"abhinand123"
}
